repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: bin/mise exec -- swiftformat
        language: system
        types: [swift]

      - id: swiftlint
        name: SwiftLint
        entry: bin/mise exec -- swiftlint lint --strict
        language: system
        types: [swift]
